name: Notion PR Auto Link

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]

jobs:
  link-to-notion:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Link PR to Notion
        uses: low2xxx/notion-pr-auto-link@main
        env:
          # 必須設定
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PR_DB_ID: ${{ secrets.NOTION_PR_DB_ID }}
          NOTION_TASK_DB_ID: ${{ secrets.NOTION_TASK_DB_ID }}
          
          # オプション設定の例（必要に応じてコメントアウトを解除）
          # TASK_ID_PREFIX: 'JIRA'  # デフォルト: 'TASK'
          # TASK_ID_PATTERN: '(CUSTOM-\d+)'  # カスタムパターン
          # PR_RELATION_PROPERTY: 'PR一覧'  # デフォルト: 'Related PRs'
          # TASK_RELATION_PROPERTY: '関連タスク'  # デフォルト: 'Related Task'