name: Notion PR Auto Link

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]

jobs:
  link-pr-to-notion:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Link PR to Notion
        uses: actions/github-script@v7
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PR_DB_ID: ${{ secrets.NOTION_PR_DB_ID }}
          NOTION_TASK_DB_ID: ${{ secrets.NOTION_TASK_DB_ID }}
          # Optional: Set task ID prefix (default: TASK)
          # TASK_ID_PREFIX: ${{ secrets.TASK_ID_PREFIX }}  # From secrets
          # TASK_ID_PREFIX: 'JIRA'  # Or hardcode if not sensitive
        with:
          script: |
            const { main } = require('./.github/scripts/notion-pr-link/main.js');
            await main(context, github);